window:
    option_as_alt: Both
    padding:
        x: 4
        y: 4
font:
    size: 14.0
    normal:
      family: Iosevka Term
      style: Regular
    bold:
      family: Iosevka Term
      style: Bold
    italic:
      family: Iosevka Term
      style: Italic
    bold_italic:
      family: Iosevka Term
      style: Bold Italic
