tap 'clojure/tools'
tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/services'

brew 'awscli'
brew 'clang-format'
brew 'clojure/tools/clojure'
brew 'cocoapods'
brew 'deno'
brew 'flyctl'
brew 'fswatch'
brew 'gcc'
brew 'go'
brew 'hugo'
brew 'llvm'
brew 'mas'
brew 'opam'
brew 'pipx'
brew 'postgresql@14'
brew 'protobuf'
brew 'python@3.9'
brew 'redis'
brew 'ripgrep'
brew 'rbenv'
brew 'ruby-build'
brew 'rust-analyzer'
brew 'starship'
brew 'tectonic'
brew 'tldr'
brew 'tokei'
brew 'tree'
brew 'volta'
brew 'wasmer'
brew 'wget'

cask '1password'
cask 'homebrew/cask-versions/adoptopenjdk8'
cask 'alacritty'
cask 'android-studio'
cask 'bartender'
cask 'calibre'
cask 'discord'
cask 'docker'
cask 'dotnet-sdk'
cask 'font-iosevka'
cask 'fork'
cask 'google-chrome'
cask 'loom'
cask 'microsoft-excel'
cask 'microsoft-powerpoint'
cask 'microsoft-teams'
cask 'microsoft-word'
cask 'microsoft-auto-update'
cask 'netnewswire'
cask 'notion'
cask 'ngrok'
cask 'nordvpn'
cask 'obs'
cask 'rapidapi'
cask 'raycast'
cask 'slack'
cask 'spotify'
cask 'telegram'
cask 'visual-studio-code'
cask 'vlc'

mas "GoodNotes", id: 1444383602
mas "HEIC Converter", id: 1294126402
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
