tap 'clojure/tools'
tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'pulumi/tap'

brew 'awscli'
brew 'clang-format'
brew 'clojure/tools/clojure'
brew 'cmake'
brew 'cocoapods'
brew 'deno'
brew 'fd'
brew 'ffmpeg'
brew 'flyctl'
brew 'fswatch'
brew 'gcc'
brew 'gh'
brew 'go'
brew 'httpie'
brew 'hugo'
brew 'imagemagick'
brew 'llvm'
brew 'mas'
brew 'opam'
brew 'pipx'
brew 'postgresql@14'
brew 'protobuf'
brew 'pulumi/tap/pulumi'
brew 'python@3.9'
brew 'redis'
brew 'ripgrep'
brew 'rbenv'
brew 'ruby-build'
brew 'rust-analyzer'
brew 'starship'
brew 'supabase'
brew 'tectonic'
brew 'tldr'
brew 'tokei'
brew 'tree'
brew 'typst'
brew 'uv'
brew 'volta'
brew 'wasmer'
brew 'wget'
brew 'zig'
brew 'zls'

cask '1password'
cask 'adoptopenjdk8'
cask 'alcove'
cask 'appcleaner'
cask 'bruno'
cask 'chatgpt'
cask 'calibre'
cask 'conductor'
cask 'cursor'
cask 'dbeaver-community'
cask 'discord'
cask 'docker-desktop'
cask 'firefox'
cask 'font-iosevka'
cask 'fork'
cask 'ghostty'
cask 'google-chrome'
cask 'jordanbaird-ice'
cask 'microsoft-excel'
cask 'microsoft-powerpoint'
cask 'microsoft-teams'
cask 'microsoft-word'
cask 'microsoft-auto-update'
cask 'mongodb-compass'
cask 'netnewswire'
cask 'ngrok'
cask 'nordvpn'
cask 'obs'
cask 'obsidian'
cask 'ollama-app'
cask 'pgadmin4'
cask 'raycast'
cask 'sf-symbols'
cask 'slack'
cask 'spotify'
cask 'telegram'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoom'

mas "AdGuard for Safari", id: 1440147259
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "WhatsApp", id: 310633997
mas "Xcode", id: 497799835

# Play https://createwithplay.com
