#!/usr/bin/env python3
"""Regenerate the Phosphor icon block at the end of theme.css.

bb draws every icon as <span data-icon="Name" data-icon-root><svg/></span>,
so a theme can swap the glyph: hide bb's svg and paint the Phosphor one as a
currentColor mask. Greptile's dashboard uses Phosphor (@phosphor-icons/react,
regular weight unless stated), so this maps bb's icon names onto it.

    python3 icons.py [path/to/@phosphor-icons/react/dist/defs]

Names missing from MAP keep bb's own icon. bb's names are its registry in
the app bundle (the core `Hn` object plus the lazy `Tn` list).
"""

import re
import sys
import urllib.parse
from pathlib import Path

DEFS = Path(sys.argv[1] if len(sys.argv) > 1 else
            Path.home() / "Repos/greptileai/greptilia/node_modules/@phosphor-icons/react/dist/defs")
CSS = Path(__file__).with_name("theme.css")
START, END = "/* <greptilian-icons> generated by icons.py */", "/* </greptilian-icons> */"

# bb icon -> Phosphor icon. Where Greptile already picks a Phosphor glyph for
# the same job (Gear, CircleNotch, Funnel, SidebarSimple, ArrowElbowDownLeft,
# LockSimple, …) that choice is used.
MAP = {
    # core
    "AlertCircle": "WarningCircle", "AlertTriangle": "Warning", "Archive": "Archive",
    "Bot": "Robot", "Bug": "Bug", "Check": "Check", "ChevronDown": "CaretDown",
    "ChevronLeft": "CaretLeft", "ChevronRight": "CaretRight", "Circle": "Circle",
    "CircleCheck": "CheckCircle", "CircleQuestion": "Question", "CircleX": "XCircle",
    "ClosePluginPane": "X", "CloseThreadPane": "X", "Code": "Code",
    "ComputerTerminal01": "TerminalWindow", "Copy": "Copy", "Download": "DownloadSimple",
    "Edit": "PencilSimple", "FilterHorizontal": "Funnel", "Folder": "Folder",
    "FolderExport": "FolderOpen", "FolderGit": "FolderSimple", "FolderPlus": "FolderPlus",
    "FolderSync": "FolderSimpleDashed", "FolderUnknown": "FolderDashed", "Folder02": "FolderSimple",
    "Info": "Info", "ListTodo": "ListChecks", "Loading": "CircleNotch",
    "MessageQuestion": "ChatCircleDots", "MessageCirclePlus": "NotePencil",
    "MessageSquarePlus": "NotePencil", "MessageSquare": "Chat", "MoreHorizontal": "DotsThree",
    "PanelLeft": "SidebarSimple", "Search": "MagnifyingGlass", "SectionAdd": "ListPlus",
    "SectionMove": "ArrowSquareRight", "Settings": "Gear", "SlidersHorizontal": "SlidersHorizontal",
    "Spinner": "CircleNotch", "Target": "Crosshair", "Terminal": "Terminal", "Toolbox": "Toolbox",
    "ToolCase": "Wrench", "Trash2": "Trash", "Unavailable": "Prohibit", "UserRoundPlus": "UserPlus",
    "Workflow": "FlowArrow", "X": "X", "Zap": "Lightning",
    # extended
    "AiBrain01": "Brain", "AiBrowser": "Browser", "AiContentGenerator01": "Sparkle",
    "AlignLeft": "TextAlignLeft", "AppWindow": "AppWindow", "ArchiveRestore": "ArrowCounterClockwise",
    "ArrowDown": "ArrowDown", "ArrowLeft": "ArrowLeft", "ArrowRight": "ArrowRight",
    "ArrowReloadHorizontal": "ArrowsClockwise", "ArrowUp": "ArrowUp", "ArrowUpDown": "ArrowsDownUp",
    "ArrowTurnBackward": "ArrowUUpLeft", "ArrowTurnForward": "ArrowUUpRight",
    "ArrowUpRight": "ArrowUpRight", "Beaker": "Flask", "BellDot": "BellRinging", "Browser": "Browser",
    "Brain": "Brain", "Calendar": "CalendarBlank", "CalendarCheckOut02": "CalendarCheck",
    "ChartColumn": "ChartBar", "ChevronUp": "CaretUp", "ChevronsDown": "CaretDoubleDown",
    "ChevronsUp": "CaretDoubleUp", "CircleArrowShrink": "ArrowsIn", "Clean": "Broom",
    "Clock": "Clock", "ClockArrowUp": "ClockClockwise", "ClockArrowDown": "ClockCounterClockwise",
    "Cloud": "Cloud", "CloudOff": "CloudSlash", "Coffee": "Coffee", "Columns2": "Columns",
    "CornerDownLeft": "ArrowElbowDownLeft", "CornerDownRight": "ArrowElbowDownRight",
    "Discord": "DiscordLogo", "DiscordLogo": "DiscordLogo", "DateTime": "CalendarBlank",
    "Github": "GithubLogo", "GithubLogo": "GithubLogo", "DragDropHorizontal": "DotsSix",
    "DragDropVertical": "DotsSixVertical", "EditFile": "NotePencil", "ElectricPlugs": "Plugs",
    "Eye": "Eye", "EyeOff": "EyeSlash", "Explore": "Compass", "ExternalLink": "ArrowSquareOut",
    "FileDiff": "FileCode", "File": "File", "FileAttachment": "FileArrowUp",
    "FileQuestion": "FileDashed", "FileText": "FileText", "FolderOpen": "FolderOpen",
    "FolderEdit": "Folder", "FolderMinus": "FolderMinus", "Fork": "GitFork",
    "GitBranch": "GitBranch", "GitMerge": "GitMerge", "GitPullRequest": "GitPullRequest",
    "GitPullRequestArrow": "GitPullRequest", "Globe": "Globe", "GridView": "SquaresFour",
    "Laptop": "Laptop", "Layers": "Stack", "Limitation": "Gauge", "ListEnd": "Queue",
    "ListView": "ListBullets", "Lock": "LockSimple", "Mail": "Envelope", "MailOpen": "EnvelopeOpen",
    "Maximize2": "ArrowsOutSimple", "Mic": "Microphone", "Minus": "Minus",
    "Minimize2": "ArrowsInSimple", "MoveTo": "ArrowBendUpRight", "NewTab": "PlusSquare",
    "News01": "Newspaper", "PackageReceive": "Package", "Palette": "Palette",
    "PanelBottom": "SquareSplitVertical", "PanelRight": "SquareSplitHorizontal",
    "Paperclip": "Paperclip", "Pause": "Pause", "Pin": "PushPin", "PinOff": "PushPinSlash",
    "Play": "Play", "Plug02": "Plug", "Plus": "Plus", "Puzzle": "PuzzlePiece", "Repeat": "Repeat",
    "RotateCcw": "ArrowCounterClockwise", "Rows2": "Rows", "SecurityCheck": "ShieldCheck",
    "Sent": "PaperPlaneTilt", "SideChat": "ChatTeardropText", "Smartphone": "DeviceMobile",
    "Sort": "ArrowsDownUp", "SortingAZ02": "SortAscending", "SortingZA01": "SortDescending",
    "SortingOneNine": "SortAscending", "SortingNineOne": "SortDescending", "Square": "Square",
    "SquareUnlock02": "LockSimpleOpen", "Star": "Star", "TimeSchedule": "Timer",
    "UserRound": "User", "ZoomIn": "MagnifyingGlassPlus", "ZoomOut": "MagnifyingGlassMinus",
    # No Phosphor counterpart, so bb's own glyph stays:
    # GitPullRequestClosed, GitPullRequestDraft, TextWrap.
}

# bb fills these with `fill-current` (the stop button's square, status dots);
# use Phosphor's fill weight there.
FILLED = ("Square", "Circle")


def svg(name, weight):
    src = (DEFS / f"{name}.es.js").read_text()
    block = re.search(rf'"{weight}",\s*(.*?)\n  \]', src, re.S).group(1)
    els = "".join(
        f"<{tag} " + " ".join(f"{k}='{v}'" for k, v in re.findall(r'(\w+):\s*"([^"]*)"', attrs)) + "/>"
        for tag, attrs in re.findall(r'createElement\("(\w+)",\s*\{([^}]*)\}', block))
    return urllib.parse.quote(f"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 256 256'>{els}</svg>", safe="/:=', ")


def rule(selector, name, weight="regular"):
    return f'{selector} {{ --gi: url("data:image/svg+xml,{svg(name, weight)}"); }}'


roots = ", ".join(f'[data-icon="{k}"]' for k in MAP)
lines = [
    START,
    "/* ---- Phosphor icons ------------------------------------------------------",
    " * Greptile's icon set. bb's svg is hidden (keeping its box) and the Phosphor",
    " * glyph painted as a currentColor mask, so colour, size and spin classes on",
    " * the span still apply. Plugin-asset icons already paint via mask; skipped. */",
    f":is({roots})[data-icon-root]:not([data-plugin-icon-asset]) {{",
    "  background-color: currentColor;",
    "  -webkit-mask: var(--gi) center / contain no-repeat;",
    "  mask: var(--gi) center / contain no-repeat;",
    "}",
    f":is({roots})[data-icon-root]:not([data-plugin-icon-asset]) > * {{",
    "  visibility: hidden;",
    "}",
    *(rule(f'[data-icon="{k}"]', v) for k, v in MAP.items()),
    *(rule(f'[data-icon="{k}"].fill-current', MAP[k], "fill") for k in FILLED),
    END,
]

css = CSS.read_text()
if START in css:
    css = css[: css.index(START)] + css[css.index(END) + len(END) :].lstrip("\n")
CSS.write_text(css.rstrip("\n") + "\n\n" + "\n".join(lines) + "\n")
print(f"{len(MAP)} icons -> {CSS.name} ({CSS.stat().st_size // 1024} KB)")
