add_newline = false

format = "$directory$git_branch$git_status» "

[directory]
format = "$path "
style = ""

[git_branch]
format = "(\\[$branch\\] )"
symbol = ""

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold red"
